

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#  elasticsearch:
#    uris: http://localhost:9200
#  redis:
#    host: localhost
#    port: 6379
  profiles:
    active: dev
  application:
    name: @project.artifactId@
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        namespace: dev
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.profiles.active}
        refresh-enabled: true
        extension-configs:
          - data-id: ${spring.application.name}-${spring.profiles.active}.yml
            refresh: true
        enable-remote-sync-config: true
  config:
    import:
      - optional:nacos:application-${spring.profiles.active}.yml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml

server:
  port: 51938
  tomcat:
    max-http-form-post-size: 10485760

#dubbo:
#  application:
#    name: ${spring.application.name}
#    qos-enable: false
#  registry:
#    address: nacos://localhost:8848
#    username: nacos
#    password: nacos
#    parameters:
#      namespace: ${spring.cloud.nacos.discovery.namespace}
##  scan:
##    base-packages: com.fang.demo.comfangdemoupms.service
#  protocol:
#    name: dubbo
#    port: -1


#MINIO 本机
#oss:
#  name: minio
#  accessKey: zbvGfcg0SDl06mD2uJdX
#  secretKey: gRoVoeFu6q5jvPAShLFPnjFx005VkPuQkC8k1h8P
#  bucketName: screw-it-development-blog-buck
#  endpoint: http://localhost:9000
#  fileExt: png,jpg,jpeg,pdf

#  MINIO 实习机
#oss:
#  name: minio
#  accessKey: fMNacdYkjR9vLglCjPpt
#  secretKey: iJfnvmKVo3TEJQQv9fIRoGKrhn2aW8NaR5bXX8m6
#  bucketName: screw-it-development-blog-buck
#  endpoint: http://localhost:9000
#  fileExt: png,jpg,jpeg,pdf

