server:
  port: 61237


spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  application:
    name: @project.artifactId@
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        namespace: dev
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.profiles.active}
        refresh-enabled: true
        extension-configs:
          - data-id: ${spring.application.name}-${spring.profiles.active}.yml
            refresh: true
        enable-remote-sync-config: true
    gateway:
      routes:
        - id: upm
          uri: lb://screw-it-development-upm
          predicates:
            - Path=/api/upm/**
          filters:
            - StripPrefix=2

        - id: consumer
          uri: lb://screw-it-development-consumer
          predicates:
            - Path=/api/consumer/**
          filters:
            - StripPrefix=2

        - id: blog
          uri: lb://screw-it-development-blog
          predicates:
            - Path=/api/blog/**
          filters:
            - StripPrefix=1

  config:
    import:
      - optional:nacos:application-${spring.profiles.active}.yml
#      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
