version: '3.8'

services:
  # 阿里巴巴 Nacos 注册中心/配置中心
  iserver-nacos:
    env_file:
      - './nacos-standlone.env'
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: iserver-nacos
    restart: always
    ports:
      # Nacos 服务端口
      - "8848:8848"
      # grpc 连接端口,这是Nacos2.0后增加的,记得防火墙或白名单放行此端口号,否则启动报错: Client not connected, current status:STARTING
      - "9848:9848"
    volumes:
      - '${NOCOS_DATA}/logs:/home/nacos/logs'
    network_mode: 'host'
